# Generated by Django 5.0.1 on 2024-01-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rollno', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=3)),
            ],
        ),
    ]
